def dummyapi():

    api =  {
   "user1":"Sumit",
   "user2":"Yash",
   "stats":{
      "summary":{
         "total_days":496,
         "total_message":35985,
         "total_words":168265,
         "total_letters":697235
      },
      "timelineByMonth":[
         {
            "Date":"15 / 10 / 20",
            "Value":442
         },
         {
            "Date":"16 / 10 / 20",
            "Value":553
         },
         {
            "Date":"17 / 10 / 20",
            "Value":491
         },
         {
            "Date":"18 / 10 / 20",
            "Value":444
         },
         {
            "Date":"19 / 10 / 20",
            "Value":900
         },
         {
            "Date":"20 / 10 / 20",
            "Value":536
         },
         {
            "Date":"21 / 10 / 20",
            "Value":805
         },
         {
            "Date":"22 / 10 / 20",
            "Value":659
         },
         {
            "Date":"23 / 10 / 20",
            "Value":768
         },
         {
            "Date":" 24 / 10 / 20",
            "Value":495
         },
         {
            "Date":"25 / 10 / 20",
            "Value":271
         },
         {
            "Date":"26 / 10 / 20",
            "Value":650
         },
         {
            "Date":"27 / 10 / 20",
            "Value":998
         },
         {
            "Date":"28 / 10 / 20",
            "Value":864
         },
         {
            "Date":"29 / 10 / 20",
            "Value":745
         },
         {
            "Date":"30 / 10 / 20",
            "Value":233
         },
         {
            "Date":"31 / 10 / 20",
            "Value":544
         },
         {
            "Date":"01 / 11 / 20",
            "Value":466
         },
         {
            "Date":"02 / 11 / 20",
            "Value":138
         },
         {
            "Date":"03 / 11 / 20",
            "Value":183
         },
         {
            "Date":"04 / 11 / 20",
            "Value":646
         },
         {
            "Date":"05 / 11 / 20",
            "Value":802
         },
         {
            "Date":"06 / 11 / 20",
            "Value":377
         },
         {
            "Date":"07 / 11 / 20",
            "Value":763
         },
         {
            "Date":"08 / 11 / 20",
            "Value":637
         },
         {
            "Date":"09 / 11 / 20",
            "Value":389
         },
         {
            "Date":"10 / 11 / 20",
            "Value":451
         },
         {
            "Date":"11 / 11 / 20",
            "Value":845
         },
         {
            "Date":"12 / 11 / 20",
            "Value":231
         },
         {
            "Date":"13 / 11 / 20",
            "Value":397
         },
         {
            "Date":"14 / 11 / 20",
            "Value":261
         },
         {
            "Date":"15 / 11 / 20",
            "Value":244
         },
         {
            "Date":"16 / 11 / 20",
            "Value":194
         },
         {
            "Date":"17 / 11 / 20",
            "Value":247
         },
         {
            "Date":"18 / 11 / 20",
            "Value":180
         },
         {
            "Date":"19/11/20",
            "Value":1488
         },
         {
            "Date":"20 / 11 / 20",
            "Value":596
         },
         {
            "Date":"21 / 11 / 20",
            "Value":744
         },
         {
            "Date":"22 / 11 / 20",
            "Value":265
         },
         {
            "Date":" 23 / 11 / 20",
            "Value":368
         },
         {
            "Date":"24 / 11 / 20",
            "Value":250
         },
         {
            "Date":"25 / 11 / 20",
            "Value":555
         },
         {
            "Date":"26 / 11 / 20",
            "Value":736
         },
         {
            "Date":"27 / 11 / 20",
            "Value":436
         },
         {
            "Date":"28 / 11 / 20",
            "Value":699
         },
         {
            "Date":"29 / 11 / 20",
            "Value":427
         },
         {
            "Date":"30 / 11 / 20",
            "Value":335
         },
         {
            "Date":"01 / 12 / 20",
            "Value":158
         },
         {
            "Date":"02 / 12 / 20",
            "Value":540
         },
         {
            "Date":"03 / 12 / 20",
            "Value":783
         },
         {
            "Date":"04 / 12 / 20",
            "Value":1083
         },
         {
            "Date":"05 / 12 / 20",
            "Value":497
         },
         {
            "Date":"06 / 12 / 20",
            "Value":303
         },
         {
            "Date":"07 / 12 / 20",
            "Value":443
         },
         {
            "Date":"08 / 12 / 20",
            "Value":755
         },
         {
            "Date":"09 / 12 / 20",
            "Value":472
         },
         {
            "Date":"10 / 12 / 20",
            "Value":137
         },
         {
            "Date":"11 / 12 / 20",
            "Value":335
         },
         {
            "Date":"12 / 12 / 20",
            "Value":452
         },
         {
            "Date":"13 / 12 / 20",
            "Value":118
         },
         {
            "Date":"14 / 12 / 20",
            "Value":450
         },
         {
            "Date":"15 / 12 / 20",
            "Value":567
         },
         {
            "Date":"16 / 12 / 20",
            "Value":207
         },
         {
            "Date":"17 / 12 / 20",
            "Value":375
         },
         {
            "Date":"18/12 / 20",
            "Value":142
         },
         {
            "Date":"19/12 / 20",
            "Value":729
         },
         {
            "Date":"20 / 12 / 20",
            "Value":669
         },
         {
            "Date":"21 / 12 / 20",
            "Value":701
         },
         {
            "Date":"22 / 12 / 20",
            "Value":336
         },
         {
            "Date":"23 / 12 / 20",
            "Value":460
         },
         {
            "Date":"24 / 12 / 20",
            "Value":373
         },
         {
            "Date":"25 / 12 / 20",
            "Value":264
         },
         {
            "Date":"26 / 12 / 20",
            "Value":330
         },
         {
            "Date":"27 / 12 / 20",
            "Value":399
         },
         {
            "Date":"28 / 12 / 20",
            "Value":223
         },
         {
            "Date":"29 / 12 / 20",
            "Value":317
         },
         {
            "Date":"30 / 12 / 20",
            "Value":179
         },
         {
            "Date":"31 / 12 / 20",
            "Value":477
         },
         {
            "Date":"01 / 01 / 21",
            "Value":328
         },
         {
            "Date":"02 / 01 / 21",
            "Value":566
         },
         {
            "Date":"03 / 01 / 21",
            "Value":196
         },
         {
            "Date":"04 / 01 / 21",
            "Value":257
         },
         {
            "Date":"05 / 01 / 21",
            "Value":428
         },
         {
            "Date":"06 / 01 / 21",
            "Value":200
         }
      ],
      "analysis":{
         "basedOnDays":{
            "all":{
               "days":[
                  {
                     "day":"Monday",
                     "value":5667,
                     "frequency":54
                  },
                  {
                     "day":"Tuesday",
                     "value":5661,
                     "frequency":54
                  },
                  {
                     "day":"Wednesday",
                     "value":4232,
                     "frequency":52
                  },
                  {
                     "day":"Thursay",
                     "value":3841,
                     "frequency":54
                  },
                  {
                     "day":"Friday",
                     "value":4523,
                     "frequency":57
                  },
                  {
                     "day":"Saturday",
                     "value":8965,
                     "frequency":67
                  },
                  {
                     "day":"Sunday",
                     "value":7856,
                     "frequency":53
                  }
               ],
               "mostActiveDay":"Saturday",
               "mostFrequentDay":"Saturday",
               "averageTexts":5820
            },
            "sumit":{
               "days":[
                  {
                     "day":"Monday",
                     "value":57,
                     "frequency":54
                  },
                  {
                     "day":"Tuesday",
                     "value":51,
                     "frequency":54
                  },
                  {
                     "day":"Wednesday",
                     "value":42,
                     "frequency":52
                  },
                  {
                     "day":"Thursay",
                     "value":1,
                     "frequency":54
                  },
                  {
                     "day":"Friday",
                     "value":43,
                     "frequency":57
                  },
                  {
                     "day":"Saturday",
                     "value":85,
                     "frequency":67
                  },
                  {
                     "day":"Sunday",
                     "value":76,
                     "frequency":53
                  }
               ],
               "mostActiveDay":"Monday",
               "mostFrequentDay":"Sunday",
               "averageTexts":124
            },
            "yash":{
               "days":[
                  {
                     "day":"Monday",
                     "value":5667,
                     "frequency":54
                  },
                  {
                     "day":"Tuesday",
                     "value":5661,
                     "frequency":54
                  },
                  {
                     "day":"Wednesday",
                     "value":4232,
                     "frequency":52
                  },
                  {
                     "day":"Thursay",
                     "value":3841,
                     "frequency":54
                  },
                  {
                     "day":"Friday",
                     "value":4523,
                     "frequency":57
                  },
                  {
                     "day":"Saturday",
                     "value":8965,
                     "frequency":67
                  },
                  {
                     "day":"Sunday",
                     "value":7856,
                     "frequency":53
                  }
               ],
               "mostActiveDay":"Saturday",
               "mostFrequentDay":"Saturday",
               "averageTexts":5820
            },
            "atharva":{
               "days":[
                  {
                     "day":"Monday",
                     "value":5667,
                     "frequency":54
                  },
                  {
                     "day":"Tuesday",
                     "value":5661,
                     "frequency":54
                  },
                  {
                     "day":"Wednesday",
                     "value":4232,
                     "frequency":52
                  },
                  {
                     "day":"Thursay",
                     "value":3841,
                     "frequency":54
                  },
                  {
                     "day":"Friday",
                     "value":4523,
                     "frequency":57
                  },
                  {
                     "day":"Saturday",
                     "value":8965,
                     "frequency":67
                  },
                  {
                     "day":"Sunday",
                     "value":7856,
                     "frequency":53
                  }
               ],
               "mostActiveDay":"Saturday",
               "mostFrequentDay":"Saturday",
               "averageTexts":5820
            },
            "purva":{
               "days":[
                  {
                     "day":"Monday",
                     "value":0,
                     "frequency":54
                  },
                  {
                     "day":"Tuesday",
                     "value":0,
                     "frequency":54
                  },
                  {
                     "day":"Wednesday",
                     "value":0,
                     "frequency":52
                  },
                  {
                     "day":"Thursay",
                     "value":3841,
                     "frequency":54
                  },
                  {
                     "day":"Friday",
                     "value":4523,
                     "frequency":57
                  },
                  {
                     "day":"Saturday",
                     "value":8965,
                     "frequency":67
                  },
                  {
                     "day":"Sunday",
                     "value":7856,
                     "frequency":53
                  }
               ],
               "mostActiveDay":"Saturday",
               "mostFrequentDay":"Saturday",
               "averageTexts":5820
            }
         },
         "basedOnTime":{
            "all":{
               "time":[
                  {
                     "day":"1h",
                     "value":56,
                     "frequency":2
                  },
                  {
                     "day":"2h",
                     "value":51,
                     "frequency":2
                  },
                  {
                     "day":"3h",
                     "value":4,
                     "frequency":1
                  },
                  {
                     "day":"4h",
                     "value":0,
                     "frequency":0
                  },
                  {
                     "day":"5h",
                     "value":0,
                     "frequency":0
                  },
                  {
                     "day":"6h",
                     "value":89,
                     "frequency":6
                  },
                  {
                     "day":"7h",
                     "value":785,
                     "frequency":53
                  },
                  {
                     "day":"8h",
                     "value":675,
                     "frequency":51
                  },
                  {
                     "day":"9h",
                     "value":2325,
                     "frequency":513
                  },
                  {
                     "day":"10h",
                     "value":4511,
                     "frequency":122
                  },
                  {
                     "day":"11h",
                     "value":6454,
                     "frequency":442
                  },
                  {
                     "day":"12h",
                     "value":4521,
                     "frequency":541
                  },
                  {
                     "day":"13h",
                     "value":5412,
                     "frequency":123
                  },
                  {
                     "day":"14h",
                     "value":4520,
                     "frequency":745
                  },
                  {
                     "day":"15h",
                     "value":7855,
                     "frequency":321
                  },
                  {
                     "day":"16h",
                     "value":7858,
                     "frequency":534
                  },
                  {
                     "day":"17h",
                     "value":8454,
                     "frequency":344
                  },
                  {
                     "day":"18h",
                     "value":7855,
                     "frequency":534
                  },
                  {
                     "day":"19h",
                     "value":7854,
                     "frequency":534
                  },
                  {
                     "day":"20h",
                     "value":1885,
                     "frequency":241
                  },
                  {
                     "day":"21h",
                     "value":4552,
                     "frequency":511
                  },
                  {
                     "day":"22h",
                     "value":2313,
                     "frequency":231
                  },
                  {
                     "day":"23h",
                     "value":4512,
                     "frequency":236
                  },
                  {
                     "day":"24h",
                     "value":8595,
                     "frequency":238
                  }
               ],
               "mostActiveTime":"Saturday",
               "mostFrequentTime":"Saturday",
               "averageTexts":5820
            },
            "sumit":{
               "time":[
                  {
                     "day":"1h",
                     "value":56,
                     "frequency":2
                  },
                  {
                     "day":"2h",
                     "value":51,
                     "frequency":2
                  },
                  {
                     "day":"3h",
                     "value":4,
                     "frequency":1
                  },
                  {
                     "day":"4h",
                     "value":0,
                     "frequency":0
                  },
                  {
                     "day":"5h",
                     "value":0,
                     "frequency":0
                  },
                  {
                     "day":"6h",
                     "value":89,
                     "frequency":6
                  },
                  {
                     "day":"7h",
                     "value":785,
                     "frequency":53
                  },
                  {
                     "day":"8h",
                     "value":675,
                     "frequency":51
                  },
                  {
                     "day":"9h",
                     "value":2325,
                     "frequency":513
                  },
                  {
                     "day":"10h",
                     "value":4511,
                     "frequency":122
                  },
                  {
                     "day":"11h",
                     "value":6454,
                     "frequency":442
                  },
                  {
                     "day":"12h",
                     "value":4521,
                     "frequency":541
                  },
                  {
                     "day":"13h",
                     "value":5412,
                     "frequency":123
                  },
                  {
                     "day":"14h",
                     "value":4520,
                     "frequency":745
                  },
                  {
                     "day":"15h",
                     "value":7855,
                     "frequency":321
                  },
                  {
                     "day":"16h",
                     "value":7858,
                     "frequency":534
                  },
                  {
                     "day":"17h",
                     "value":8454,
                     "frequency":344
                  },
                  {
                     "day":"18h",
                     "value":7855,
                     "frequency":534
                  },
                  {
                     "day":"19h",
                     "value":7854,
                     "frequency":534
                  },
                  {
                     "day":"20h",
                     "value":1885,
                     "frequency":241
                  },
                  {
                     "day":"21h",
                     "value":4552,
                     "frequency":511
                  },
                  {
                     "day":"22h",
                     "value":2313,
                     "frequency":231
                  },
                  {
                     "day":"23h",
                     "value":4512,
                     "frequency":236
                  },
                  {
                     "day":"24h",
                     "value":8595,
                     "frequency":238
                  }
               ],
               "mostActiveTime":"Saturday",
               "mostFrequentTime":"Saturday",
               "averageTexts":5820
            },
            "yash":{
               "time":[
                  {
                     "day":"1h",
                     "value":56,
                     "frequency":2
                  },
                  {
                     "day":"2h",
                     "value":51,
                     "frequency":2
                  },
                  {
                     "day":"3h",
                     "value":4,
                     "frequency":1
                  },
                  {
                     "day":"4h",
                     "value":0,
                     "frequency":0
                  },
                  {
                     "day":"5h",
                     "value":0,
                     "frequency":0
                  },
                  {
                     "day":"6h",
                     "value":89,
                     "frequency":6
                  },
                  {
                     "day":"7h",
                     "value":785,
                     "frequency":53
                  },
                  {
                     "day":"8h",
                     "value":675,
                     "frequency":51
                  },
                  {
                     "day":"9h",
                     "value":2325,
                     "frequency":513
                  },
                  {
                     "day":"10h",
                     "value":4511,
                     "frequency":122
                  },
                  {
                     "day":"11h",
                     "value":6454,
                     "frequency":442
                  },
                  {
                     "day":"12h",
                     "value":4521,
                     "frequency":541
                  },
                  {
                     "day":"13h",
                     "value":5412,
                     "frequency":123
                  },
                  {
                     "day":"14h",
                     "value":4520,
                     "frequency":745
                  },
                  {
                     "day":"15h",
                     "value":7855,
                     "frequency":321
                  },
                  {
                     "day":"16h",
                     "value":7858,
                     "frequency":534
                  },
                  {
                     "day":"17h",
                     "value":8454,
                     "frequency":344
                  },
                  {
                     "day":"18h",
                     "value":7855,
                     "frequency":534
                  },
                  {
                     "day":"19h",
                     "value":7854,
                     "frequency":534
                  },
                  {
                     "day":"20h",
                     "value":1885,
                     "frequency":241
                  },
                  {
                     "day":"21h",
                     "value":4552,
                     "frequency":511
                  },
                  {
                     "day":"22h",
                     "value":2313,
                     "frequency":231
                  },
                  {
                     "day":"23h",
                     "value":4512,
                     "frequency":236
                  },
                  {
                     "day":"24h",
                     "value":8595,
                     "frequency":238
                  }
               ],
               "mostActiveTime":"Saturday",
               "mostFrequentTime":"Saturday",
               "averageTexts":5820
            }
         }
      },
      "emoji":[
         {
            "Emoji":"😭",
            "No_Of_Emoji":465
         },
         {
            "Emoji":"😳",
            "No_Of_Emoji":378
         },
         {
            "Emoji":"😂",
            "No_Of_Emoji":349
         },
         {
            "Emoji":"👀",
            "No_Of_Emoji":200
         },
         {
            "Emoji":"😜",
            "No_Of_Emoji":191
         },
         {
            "Emoji":"🤣",
            "No_Of_Emoji":178
         },
         {
            "Emoji":"➖",
            "No_Of_Emoji":75
         },
         {
            "Emoji":"🥳",
            "No_Of_Emoji":72
         },
         {
            "Emoji":"🥺",
            "No_Of_Emoji":64
         },
         {
            "Emoji":"🌚",
            "No_Of_Emoji":61
         },
         {
            "Emoji":"❤",
            "No_Of_Emoji":59
         },
         {
            "Emoji":"🤮",
            "No_Of_Emoji":54
         },
         {
            "Emoji":"😤",
            "No_Of_Emoji":53
         },
         {
            "Emoji":"🇮",
            "No_Of_Emoji":48
         },
         {
            "Emoji":"😫",
            "No_Of_Emoji":48
         },
         {
            "Emoji":"🤤",
            "No_Of_Emoji":47
         },
         {
            "Emoji":"🥵",
            "No_Of_Emoji":47
         },
         {
            "Emoji":"🏻",
            "No_Of_Emoji":45
         },
         {
            "Emoji":"🇳",
            "No_Of_Emoji":44
         },
         {
            "Emoji":"😔",
            "No_Of_Emoji":41
         }
      ],
      "heatmap":[
         {
            "DATE":"11-19-20",
            "FREQUENCY":1488
         },
         {
            "DATE":"12-4-20",
            "FREQUENCY":1083
         },
         {
            "DATE":"10-27-20",
            "FREQUENCY":997
         },
         {
            "DATE":"10-28-20",
            "FREQUENCY":864
         },
         {
            "DATE":"11-11-20",
            "FREQUENCY":845
         },
         {
            "DATE":"10-21-20",
            "FREQUENCY":805
         },
         {
            "DATE":"11-5-20",
            "FREQUENCY":802
         },
         {
            "DATE":"12-3-20",
            "FREQUENCY":786
         },
         {
            "DATE":"10-23-20",
            "FREQUENCY":768
         },
         {
            "DATE":"11-7-20",
            "FREQUENCY":762
         },
         {
            "DATE":"12-8-20",
            "FREQUENCY":755
         },
         {
            "DATE":"12-19-20",
            "FREQUENCY":752
         },
         {
            "DATE":"10-29-20",
            "FREQUENCY":744
         },
         {
            "DATE":"11-21-20",
            "FREQUENCY":741
         },
         {
            "DATE":"11-26-20",
            "FREQUENCY":736
         },
         {
            "DATE":"11-28-20",
            "FREQUENCY":698
         },
         {
            "DATE":"12-20-20",
            "FREQUENCY":669
         },
         {
            "DATE":"10-22-20",
            "FREQUENCY":659
         },
         {
            "DATE":"10-26-20",
            "FREQUENCY":650
         },
         {
            "DATE":"11-4-20",
            "FREQUENCY":645
         },
         {
            "DATE":"11-8-20",
            "FREQUENCY":637
         },
         {
            "DATE":"11-20-20",
            "FREQUENCY":597
         },
         {
            "DATE":"12-15-20",
            "FREQUENCY":567
         },
         {
            "DATE":"1-2-21",
            "FREQUENCY":565
         },
         {
            "DATE":"11-25-20",
            "FREQUENCY":555
         },
         {
            "DATE":"1-6-21",
            "FREQUENCY":551
         },
         {
            "DATE":"10-31-20",
            "FREQUENCY":544
         },
         {
            "DATE":"12-2-20",
            "FREQUENCY":540
         },
         {
            "DATE":"10-20-20",
            "FREQUENCY":536
         },
         {
            "DATE":"10-19-20",
            "FREQUENCY":520
         },
         {
            "DATE":"12-21-20",
            "FREQUENCY":519
         },
         {
            "DATE":"12-5-20",
            "FREQUENCY":497
         },
         {
            "DATE":"10-24-20",
            "FREQUENCY":494
         },
         {
            "DATE":"12-31-20",
            "FREQUENCY":477
         },
         {
            "DATE":"12-9-20",
            "FREQUENCY":471
         },
         {
            "DATE":"11-1-20",
            "FREQUENCY":466
         },
         {
            "DATE":"1-11-21",
            "FREQUENCY":466
         },
         {
            "DATE":"12-23-20",
            "FREQUENCY":459
         },
         {
            "DATE":"12-12-20",
            "FREQUENCY":452
         },
         {
            "DATE":"11-10-20",
            "FREQUENCY":451
         },
         {
            "DATE":"12-14-20",
            "FREQUENCY":450
         },
         {
            "DATE":"12-7-20",
            "FREQUENCY":443
         },
         {
            "DATE":"11-27-20",
            "FREQUENCY":436
         },
         {
            "DATE":"1-5-21",
            "FREQUENCY":428
         },
         {
            "DATE":"11-29-20",
            "FREQUENCY":427
         },
         {
            "DATE":"1-8-21",
            "FREQUENCY":401
         },
         {
            "DATE":"12-27-20",
            "FREQUENCY":399
         },
         {
            "DATE":"1-7-21",
            "FREQUENCY":399
         },
         {
            "DATE":"11-13-20",
            "FREQUENCY":397
         },
         {
            "DATE":"11-9-20",
            "FREQUENCY":389
         },
         {
            "DATE":"11-6-20",
            "FREQUENCY":377
         },
         {
            "DATE":"12-17-20",
            "FREQUENCY":375
         },
         {
            "DATE":"12-24-20",
            "FREQUENCY":373
         },
         {
            "DATE":"11-23-20",
            "FREQUENCY":368
         },
         {
            "DATE":"1-10-21",
            "FREQUENCY":354
         },
         {
            "DATE":"1-9-21",
            "FREQUENCY":338
         },
         {
            "DATE":"11-30-20",
            "FREQUENCY":335
         },
         {
            "DATE":"12-11-20",
            "FREQUENCY":335
         },
         {
            "DATE":"12-26-20",
            "FREQUENCY":329
         },
         {
            "DATE":"1-1-21",
            "FREQUENCY":328
         },
         {
            "DATE":"12-29-20",
            "FREQUENCY":317
         },
         {
            "DATE":"12-6-20",
            "FREQUENCY":303
         },
         {
            "DATE":"1-12-21",
            "FREQUENCY":281
         },
         {
            "DATE":"10-25-20",
            "FREQUENCY":271
         },
         {
            "DATE":"11-22-20",
            "FREQUENCY":265
         },
         {
            "DATE":"12-25-20",
            "FREQUENCY":264
         },
         {
            "DATE":"11-14-20",
            "FREQUENCY":261
         },
         {
            "DATE":"1-4-21",
            "FREQUENCY":257
         },
         {
            "DATE":"11-24-20",
            "FREQUENCY":250
         },
         {
            "DATE":"11-17-20",
            "FREQUENCY":247
         },
         {
            "DATE":"11-15-20",
            "FREQUENCY":244
         },
         {
            "DATE":"10-30-20",
            "FREQUENCY":233
         },
         {
            "DATE":"11-12-20",
            "FREQUENCY":231
         },
         {
            "DATE":"12-28-20",
            "FREQUENCY":223
         },
         {
            "DATE":"12-16-20",
            "FREQUENCY":207
         },
         {
            "DATE":"1-3-21",
            "FREQUENCY":196
         },
         {
            "DATE":"11-16-20",
            "FREQUENCY":194
         },
         {
            "DATE":"11-3-20",
            "FREQUENCY":183
         },
         {
            "DATE":"11-18-20",
            "FREQUENCY":180
         },
         {
            "DATE":"12-30-20",
            "FREQUENCY":179
         },
         {
            "DATE":"12-22-20",
            "FREQUENCY":170
         },
         {
            "DATE":"12-1-20",
            "FREQUENCY":158
         },
         {
            "DATE":"12-18-20",
            "FREQUENCY":142
         },
         {
            "DATE":"11-2-20",
            "FREQUENCY":138
         },
         {
            "DATE":"12-10-20",
            "FREQUENCY":137
         },
         {
            "DATE":"12-13-20",
            "FREQUENCY":120
         },
         {
            "DATE":"1-13-21",
            "FREQUENCY":41
         }
      ],
      "wordcloud":[
         {
            "FREQUENCY":8816,
            "WORD":"h"
         },
         {
            "FREQUENCY":5042,
            "WORD":"hod"
         },
         {
            "FREQUENCY":5023,
            "WORD":"cha"
         },
         {
            "FREQUENCY":4169,
            "WORD":"<media"
         },
         {
            "FREQUENCY":4169,
            "WORD":"omitted>"
         },
         {
            "FREQUENCY":1358,
            "WORD":"hain"
         },
         {
            "FREQUENCY":1247,
            "WORD":"kya"
         },
         {
            "FREQUENCY":1138,
            "WORD":"ka"
         },
         {
            "FREQUENCY":1054,
            "WORD":"and"
         },
         {
            "FREQUENCY":995,
            "WORD":"bc"
         },
         {
            "FREQUENCY":876,
            "WORD":"toh"
         },
         {
            "FREQUENCY":829,
            "WORD":"to"
         },
         {
            "FREQUENCY":827,
            "WORD":"rha"
         },
         {
            "FREQUENCY":780,
            "WORD":"na"
         },
         {
            "FREQUENCY":776,
            "WORD":"i"
         },
         {
            "FREQUENCY":761,
            "WORD":"nahi"
         },
         {
            "FREQUENCY":754,
            "WORD":"tha"
         },
         {
            "FREQUENCY":729,
            "WORD":"bhi"
         },
         {
            "FREQUENCY":677,
            "WORD":"ko"
         },
         {
            "FREQUENCY":645,
            "WORD":"se"
         },
         {
            "FREQUENCY":645,
            "WORD":"the"
         },
         {
            "FREQUENCY":640,
            "WORD":"yash"
         },
         {
            "FREQUENCY":624,
            "WORD":"but"
         },
         {
            "FREQUENCY":601,
            "WORD":"kar"
         },
         {
            "FREQUENCY":594,
            "WORD":"you"
         },
         {
            "FREQUENCY":578,
            "WORD":"https"
         },
         {
            "FREQUENCY":572,
            "WORD":"is"
         },
         {
            "FREQUENCY":564,
            "WORD":"xd"
         },
         {
            "FREQUENCY":540,
            "WORD":"main"
         },
         {
            "FREQUENCY":527,
            "WORD":"abhi"
         },
         {
            "FREQUENCY":526,
            "WORD":"yes"
         },
         {
            "FREQUENCY":520,
            "WORD":"this"
         },
         {
            "FREQUENCY":512,
            "WORD":"@917020037195"
         },
         {
            "FREQUENCY":505,
            "WORD":"haa"
         },
         {
            "FREQUENCY":492,
            "WORD":"ho"
         },
         {
            "FREQUENCY":489,
            "WORD":"nice"
         },
         {
            "FREQUENCY":485,
            "WORD":"bhai"
         },
         {
            "FREQUENCY":485,
            "WORD":"like"
         },
         {
            "FREQUENCY":483,
            "WORD":"ke"
         },
         {
            "FREQUENCY":483,
            "WORD":"hi"
         },
         {
            "FREQUENCY":445,
            "WORD":"@918602842290"
         },
         {
            "FREQUENCY":441,
            "WORD":"nhhi"
         },
         {
            "FREQUENCY":433,
            "WORD":"in"
         },
         {
            "FREQUENCY":429,
            "WORD":"me"
         },
         {
            "FREQUENCY":423,
            "WORD":"kia"
         },
         {
            "FREQUENCY":423,
            "WORD":"for"
         },
         {
            "FREQUENCY":415,
            "WORD":"mai"
         },
         {
            "FREQUENCY":403,
            "WORD":"ye"
         },
         {
            "FREQUENCY":397,
            "WORD":"a"
         },
         {
            "FREQUENCY":393,
            "WORD":"'no_of_emoji'"
         },
         {
            "FREQUENCY":392,
            "WORD":"{'emoji'"
         },
         {
            "FREQUENCY":382,
            "WORD":"we"
         },
         {
            "FREQUENCY":380,
            "WORD":"no"
         },
         {
            "FREQUENCY":374,
            "WORD":"@918446224700"
         },
         {
            "FREQUENCY":372,
            "WORD":"tu"
         },
         {
            "FREQUENCY":368,
            "WORD":"ki"
         },
         {
            "FREQUENCY":362,
            "WORD":"k"
         },
         {
            "FREQUENCY":347,
            "WORD":"of"
         },
         {
            "FREQUENCY":346,
            "WORD":"karna"
         },
         {
            "FREQUENCY":346,
            "WORD":"vo"
         },
         {
            "FREQUENCY":340,
            "WORD":"mera"
         },
         {
            "FREQUENCY":335,
            "WORD":"kuch"
         },
         {
            "FREQUENCY":327,
            "WORD":"ok"
         },
         {
            "FREQUENCY":319,
            "WORD":"are"
         },
         {
            "FREQUENCY":319,
            "WORD":"hu"
         },
         {
            "FREQUENCY":316,
            "WORD":"be"
         },
         {
            "FREQUENCY":314,
            "WORD":"what"
         },
         {
            "FREQUENCY":310,
            "WORD":"it"
         },
         {
            "FREQUENCY":306,
            "WORD":"was"
         },
         {
            "FREQUENCY":304,
            "WORD":"can"
         },
         {
            "FREQUENCY":293,
            "WORD":"bahut"
         },
         {
            "FREQUENCY":287,
            "WORD":"so"
         },
         {
            "FREQUENCY":286,
            "WORD":"on"
         },
         {
            "FREQUENCY":286,
            "WORD":"ek"
         },
         {
            "FREQUENCY":284,
            "WORD":"pe"
         },
         {
            "FREQUENCY":274,
            "WORD":"hua"
         },
         {
            "FREQUENCY":266,
            "WORD":"time"
         },
         {
            "FREQUENCY":261,
            "WORD":"not"
         },
         {
            "FREQUENCY":260,
            "WORD":"xddd"
         },
         {
            "FREQUENCY":259,
            "WORD":"gaya"
         },
         {
            "FREQUENCY":256,
            "WORD":"kal"
         },
         {
            "FREQUENCY":253,
            "WORD":"that"
         },
         {
            "FREQUENCY":248,
            "WORD":"bola"
         },
         {
            "FREQUENCY":242,
            "WORD":"yeh"
         },
         {
            "FREQUENCY":242,
            "WORD":"do"
         },
         {
            "FREQUENCY":238,
            "WORD":"n"
         },
         {
            "FREQUENCY":230,
            "WORD":"mujhe"
         },
         {
            "FREQUENCY":229,
            "WORD":"wtf"
         },
         {
            "FREQUENCY":228,
            "WORD":"he"
         },
         {
            "FREQUENCY":222,
            "WORD":"m"
         },
         {
            "FREQUENCY":221,
            "WORD":"acha"
         },
         {
            "FREQUENCY":221,
            "WORD":"karte"
         },
         {
            "FREQUENCY":218,
            "WORD":"code"
         },
         {
            "FREQUENCY":218,
            "WORD":"bol"
         },
         {
            "FREQUENCY":217,
            "WORD":"aaj"
         },
         {
            "FREQUENCY":215,
            "WORD":"?"
         },
         {
            "FREQUENCY":213,
            "WORD":"yaar"
         },
         {
            "FREQUENCY":213,
            "WORD":"hota"
         },
         {
            "FREQUENCY":212,
            "WORD":"kr"
         },
         {
            "FREQUENCY":210,
            "WORD":"sab"
         }
      ],
      "userSpecific":[
         {
            "totalDays":450,
            "totalMessageExchanged":3598,
            "averageTexts":124,
            "highestStreak":12,
            "streakRange":{
               "startDate":"12-12-20",
               "endDate":"24-12-20"
            },
            "mostUsedWord":"lol",
            "mostUsedEmoji":"😳",
            "name":"Sumit",
            "speciality":"Highest Emoji Texter"
         },
         {
            "totalDays":398,
            "totalMessageExchanged":2564,
            "averageTexts":78,
            "highestStreak":6,
            "streakRange":{
               "startDate":"12-12-20",
               "endDate":"24-12-20"
            },
            "mostUsedWord":"haa",
            "mostUsedEmoji":"😳",
            "name":"Yash",
            "speciality":"Seen Zoner"
         },
         {
            "totalDays":453,
            "totalMessageExchanged":9458,
            "averageTexts":356,
            "highestStreak":17,
            "streakRange":{
               "startDate":"12-12-20",
               "endDate":"24-12-20"
            },
            "mostUsedWord":"lol",
            "mostUsedEmoji":"😳",
            "name":"Atharva",
            "speciality":"Spammer"
         },
         {
            "totalDays":450,
            "totalMessageExchanged":3598,
            "averageTexts":124,
            "highestStreak":12,
            "streakRange":{
               "startDate":"12-12-20",
               "endDate":"24-12-20"
            },
            "mostUsedWord":"lol",
            "mostUsedEmoji":"😳",
            "name":"Amitesh",
            "speciality":"Media MegaGod"
         },
         {
            "totalDays":450,
            "totalMessageExchanged":3598,
            "averageTexts":124,
            "highestStreak":12,
            "streakRange":{
               "startDate":"12-12-20",
               "endDate":"24-12-20"
            },
            "mostUsedWord":"lol",
            "mostUsedEmoji":"😳",
            "name":"Lubna",
            "speciality":"NULL"
         },
         {
            "totalDays":450,
            "totalMessageExchanged":3598,
            "averageTexts":124,
            "highestStreak":12,
            "streakRange":{
               "startDate":"12-12-20",
               "endDate":"24-12-20"
            },
            "mostUsedWord":"lol",
            "mostUsedEmoji":"😳",
            "name":"Tamal",
            "speciality":"LinksIn "
         }
      ]
   }
}
    return api

